import yaml
from jinja2 import Environment, FileSystemLoader
import sys

def render_template(template_path, context):
    loader = FileSystemLoader(searchpath="../../jinja_templates/ciscoxr")
    env = Environment(loader=loader)
    template = env.get_template(template_path)
    return template.render(context)

if len(sys.argv) > 1:
    device_name = sys.argv[1]
else:
    device_name = input("enter device name: ")
    
template_path = "ospf.j2"
yaml_file = f"../../yaml_files/ciscoxr/{device_name}.yaml"

with open(yaml_file, 'r') as stream:
    device_parameters = yaml.safe_load(stream)

# print('here are ospf configs')
# print(device_parameters)

context = {'ospf': device_parameters['device']['ospf']}
config_text = render_template(template_path, context)
config_text = config_text.strip()
print('here is config_text')
print(config_text)
print(type(config_text))

print('----------Displaying configs generated by OSPF config generator------------')
#print(config_text)

output_file_path = f'../../startup_configs/ciscoxr/{device_name}.conf'

with open(output_file_path, 'r') as existing_file:
    existing_lines = existing_file.readlines()

# existing_lines = [line.strip() for line in existing_lines]


# # Filter out lines that already exist in the file
# new_lines = [''] + [line.strip() for line in config_text.splitlines() if line.strip() not in existing_lines]

# print('these are the new lines')
# print(new_lines)

# Append only the new lines to the file
with open(output_file_path, 'a') as output_file:
    output_file.write('\n'+ '\n'.join(config_text.splitlines()))

with open(output_file_path, 'r') as output_file:
    device_config1 = output_file.read()

# print('full config')
# print(device_config1)

